name: Deploy FAQ & Feedback Cloud Function
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}
      - name: Install dependencies
        run: npm ci
      - name: Deploy Cloud Function (HTTP)
        run: |
          gcloud functions deploy faqFeedbackFunction             --gen2             --runtime=nodejs18             --region=${{ secrets.GCP_REGION }}             --entry-point=appFunction             --trigger-http             --service-account=${{ secrets.OPAL_SA_EMAIL }}             --set-env-vars=ENV=demo
